{% set name = "cyipopt" %}
{% set version = "1.2.0" %}
{% set sha256 = "e2da9e2e4233e01acc235bfda104e958d6cf54f7bc415d8a36677ead30f03a80" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config  # [unix]
  host:
    - cython >=0.26
    - ipopt  # [unix]
    - ipopt >=3.13  # [win]
    - libblas
    - liblapack
    - numpy
    - pip
    - python
    - setuptools >=39.0
  run:
    - {{ pin_compatible('numpy') }}
    - ipopt  # [unix]
    - ipopt >=3.13  # [win]
    - python
  run_constrained:
    - scipy >=0.11.0

test:
  requires:
    - scipy
  imports:
    - cyipopt
    - ipopt
  files:
    - examplehs071.py
  commands:
    - python examplehs071.py

about:
  home: https://github.com/mechmotum/cyipopt
  license: EPL-1.0
  license_file: LICENSE
  summary: A Cython wrapper to the IPOPT optimization package
  description: |
    Ipopt (Interior Point OPTimizer, pronounced eye-pea-Opt) is a software
    package for large-scale nonlinear optimization. cyipopt is a python wrapper
    around Ipopt. It enables using Ipopt from the comfort of the great Python
    scripting language. Ipopt is available from the COIN-OR initiative, under
    the Eclipse Public License (EPL).
  doc_url: https://cyipopt.readthedocs.io
  dev_url: https://github.com/mechmotum/cyipopt

extra:
  recipe-maintainers:
    - moorepants
