{% set name = "cyipopt" %}
{% set version = "0.3.0" %}
{% set sha256 = "fff4271c3661a4ad9fe7f0f2f0138648cd007e94c8d10ba456b56959ecee7d3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/matthias-k/cyipopt/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - no_link_gfortran.patch
    # NOTE : After cyipopt 0.3.0 was released ipopt-feedstock changed the name
    # of the shared libraries on windows from libipopt to ipopt-3, this patch
    # is required to build against the latest ipopt-feedstock built binaries.
    - setup.py.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config  # [unix]
  host:
    - cython
    - ipopt
    - libblas
    - liblapack
    - numpy
    - pip
    - python
    - scipy
    - setuptools
    - six
  run:
    - {{ pin_compatible('numpy') }}
    - future
    - ipopt
    - python
    - scipy
    - six

test:
  imports:
    - ipopt
  files:
    - examplehs071.py
  commands:
    - python examplehs071.py

about:
  home: https://github.com/mechmotum/cyipopt
  license: EPL-1.0
  license_file: LICENSE
  summary: A Cython wrapper to the IPOPT optimization package
  description: |
    Ipopt (Interior Point OPTimizer, pronounced eye-pea-Opt) is a software
    package for large-scale nonlinear optimization. cyipopt is a python wrapper
    around Ipopt. It enables using Ipopt from the comfort of the great Python
    scripting language. Ipopt is available from the COIN-OR initiative, under
    the Eclipse Public License (EPL).
  doc_url: https://cyipopt.readthedocs.io
  dev_url: https://github.com/mechmotum/cyipopt

extra:
  recipe-maintainers:
    - moorepants
