{% set name = "cyipopt" %}
{% set version = "0.1.9" %}
{% set sha256 = "b6cea96d5ffb9d3f55d993dd51575fa6137c1f94bdfd53b7b25f574989fffa38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/matthias-k/cyipopt/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
     - windows-pkg-config.patch
     - no_link_gfortran.patch  # [not win]

build:
  number: 1003
  skip: true  # [win and vc<14]

requirements:
  build:
    - pkg-config  # [osx]
    - {{ compiler('cxx') }}
    - m2-patch  # [win]
    - patch  # [not win]
  host: 
    - libpython  # [win]
    - mumps-seq  # [win]
    - ipopt
    - pip
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - six
  run:
    - python
    - ipopt
    - mumps-seq  # [win]
    - {{ pin_compatible('numpy') }}
    - scipy
    - six
    - future

test:
  imports:
    - ipopt
  files:
    - examplehs071.py
  commands:
    - python examplehs071.py

about:
  home: https://github.com/matthias-k/cyipopt
  license: EPL-1.0
  summary: 'A Cython wrapper to the IPOPT optimization package'

  description: |
    Ipopt (Interior Point OPTimizer, pronounced eye-pea-Opt) is a software
    package for large-scale nonlinear optimization. cyipopt is a python wrapper
    around Ipopt. It enables using Ipopt from the comfort of the great Python
    scripting language. Ipopt is available from the COIN-OR initiative, under
    the Eclipse Public License (EPL).
  doc_url: http://pythonhosted.org/ipopt/
  dev_url: https://github.com/matthias-k/cyipopt

extra:
  recipe-maintainers:
    - moorepants
