{% set name = "cyipopt" %}
{% set version = "1.3.0" %}
{% set sha256 = "9845524079088bc5fcb61ff35caff7c1ccf785b2d7987093f357bc29fd93c306" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: /bin/rm -f pyproject.toml && {{ PYTHON }} -m pip install . -vv  # [unix]
  skip: True  # [python_impl == 'pypy']
 
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython =0.29.*                         # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - pkg-config  # [unix]
  host:
    - cython =0.29.*  # does not build with cython >=3
    - ipopt  # [unix]
    - ipopt >=3.13  # [win]
    - libblas
    - liblapack
    - numpy
    - pip
    - python
    - setuptools >=41.1.1
  run:
    - {{ pin_compatible('numpy') }}
    - ipopt  # [unix]
    - ipopt >=3.13  # [win]
    - python
  run_constrained:
    - scipy >=1.8.0

test:
  requires:
    - scipy
  imports:
    - cyipopt
    - ipopt
  files:
    - examplehs071.py
  commands:
    - python examplehs071.py

about:
  home: https://github.com/mechmotum/cyipopt
  license: EPL-2.0
  license_file: LICENSE
  summary: A Cython wrapper to the IPOPT optimization package
  description: |
    Ipopt (Interior Point OPTimizer, pronounced eye-pea-Opt) is a software
    package for large-scale nonlinear optimization. cyipopt is a python wrapper
    around Ipopt. It enables using Ipopt from the comfort of the great Python
    scripting language. Ipopt is available from the COIN-OR initiative, under
    the Eclipse Public License (EPL).
  doc_url: https://cyipopt.readthedocs.io
  dev_url: https://github.com/mechmotum/cyipopt

extra:
  recipe-maintainers:
    - moorepants
