{% set name = "cyipopt" %}
{% set version = "1.5.0" %}
{% set sha256 = "8c6f9c1081aa754c6f84d9f2842bd0d4e4ad466a567f0d4675b124d681eec1dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: /bin/rm -f pyproject.toml && {{ PYTHON }} -m pip install . -vv  # [unix]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.28                       # [build_platform != target_platform]
    - numpy >1.25                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config  # [unix]
  host:
    - cython >=0.29.28
    - ipopt  # [unix]
    - ipopt >=3.13  # [win]
    - libblas
    - liblapack
    - numpy >=1.25
    - pip
    - python
    - setuptools >=41.1.1
  run:
    - ipopt  # [unix]
    - ipopt >=3.13  # [win]
    - numpy >=1.21.5
    - python
  run_constrained:
    - scipy >=1.8.0

test:
  requires:
    - scipy
  imports:
    - cyipopt
    - ipopt
  files:
    - examplehs071.py
  commands:
    - python examplehs071.py

about:
  home: https://github.com/mechmotum/cyipopt
  license: EPL-2.0
  license_file: LICENSE
  summary: A Cython wrapper to the IPOPT optimization package
  description: |
    Ipopt (Interior Point OPTimizer, pronounced eye-pea-Opt) is a software
    package for large-scale nonlinear optimization. cyipopt is a python wrapper
    around Ipopt. It enables using Ipopt from the comfort of the great Python
    scripting language. Ipopt is available from the COIN-OR initiative, under
    the Eclipse Public License (EPL).
  doc_url: https://cyipopt.readthedocs.io
  dev_url: https://github.com/mechmotum/cyipopt

extra:
  recipe-maintainers:
    - moorepants
