travis:
  secure:
    BINSTAR_TOKEN: goHKEXj+5rxuoYdrxkreOvBxB023S9L/gQ8fgV9zaE7h/VK/Bhryckv77gt0DQmeU3PZVHxPfGI0K0+HaH1zUajpuUU0P+Aqq74Ei6ra3HRAkviL0OJhXGB8F7jgbMtMaIKVc2XyUCdpQ28He3Cu7+1voL5v04hWM/busu/yXfIidU3ko7i7+9NuKNRcmGECmvupc5c1aRiRcVne0p6o4TW/O0l0lGhcK37qaCXfheNGRdXg75ZqtezW2BMwHlObQg6i7WnFlsFJ24u73Ap9GKXCN+0ZPZhzoObgRdg3F5t6PHwxFd+8lnl6PTmZbldLS3Nae76wMBCBgscdjWOEAsP/D1blu9Emn1TrmxMKft0lzurGERMw8me6qr8fceNke6ce8TQPVlfA6Hg2QBPCXzHF7j1ofK+ubasstQ+DZtMJng6GEnFW/NBKHY4HRS9nK+d9Ws6ySItm5u4lphPjB8oWWRYRPDfMxvxtHXPLacz/aGntUrWAMo4806Tr4d/7kEY9w0zb7i5l/NpUD+6tgmWM5LsRRLNK7yFiJCr92WwOJhjXpVnr89WTtjTWxMHfe9Ym2A0o35qKHfJmLFedu36uKqlXBEvEThSMaL5piZwUJILJHQTj+IKs9BM15TBWq1FH4BQAzNln6HvnI1bSEkipTd5myt/EDYTRNXt85Lc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
