travis:
  secure:
    BINSTAR_TOKEN: aARcjIno3HsxLie7HjDeBF+wET9GqVvz5MJteYt0DVwnxOretYcSzFRZK6RVDZbVyU1ML9dARX7ZyrfSawBoGvhQfYbHg6IIkXhTuF1C7NuK9Ujf9x6s6K7kU1LUlghjSgYPPxfdv+vD+40m5t3w5KDrPrZWRU3sCz3EdyntDOee99ugstlxaNjP4Laej5MmeZxwx4DHhFzdqJqjs0faP6JUTvncV4LTbLnrxhloJc9S6bK+P2zNf1QykieoOspTEtiX/QZD2GtJ4Y7U/EasZJualHLZdEUZKc2AuFG+/v7PA1tvHY2kzEB3eh1Mvzi+L+BZ5qpjaH7f3ku3YJkNM+U4xJmZ69nqJHQ0P9YATi0twRbvl06El1xnAM2Qk8Vpl9fmPXqYpPG4W1Y7GY/TGDaDc14hDkblnShTVInomcocNPEG6h3yMc3nsFu1xQSm6QmF0alqzI60XIXw9zLpvB77OrDYlz+c8HmUb7Mi0IFSoXx/I2ILCrTbT9rIRhnNUdctwZP8WjVSPxl2cXCd5xc84zrlJ/yAXTkKLyfymdKirE5eLkBKnV37+woFjC/0f1F3EMu9DL1vfuHXKd/XhlbBOxM95Wqd4aGZiukEJeUzhLigbHfKXzyYWqmPcPGYj0nTWNn8fn8eaa5whS4VaFRijNfTZBkCGpOJxlELT1M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
